### ISSUE TITLE
The equation of problem_weak.py in the old problem folder

### ISSUE THREAD

**Issue by Humengxian** [yaohua32/wan#1]
Hello, could you tell me about the equation and the corresponding boundary conditions in problem_weak.py? The code seems to be inconsistent with the equation in the paper

**Comment by yaohua32** [comment]
> Hello, could you tell me about the equation and the corresponding boundary conditions in problem_weak.py? The code seems to be inconsistent with the equation in the paper

**Comment by yaohua32** [comment]
> Hello, could you tell me about the equation and the corresponding boundary conditions in problem_weak.py? The code seems to be inconsistent with the equation in the paper

Thank you for pointing out this issue. The code problem_weak.py has updated now.
